---
- name: Install modsecurity core ruleset
  apt: pkg=modsecurity-crs state=latest

- name: Checking for apache2
  stat: path=/etc/apache2/apache2.conf
  register: apache_installed

- name: Install modsecurity apache mod
  apt: pkg=libapache2-mod-security2 state=latest
  when: apache_installed

- name: Enable modsecurity
  action: command a2enmod security2
  notify: Restart apache2
  when: apache_installed
  
- name: Install evasive apache mod
  apt: pkg=libapache2-mod-evasive state=latest
  when: apache_installed

- name: Enable modsecurity
  action: command a2enmod evasive
  notify: Restart apache2  
  when: apache_installed

