---
- name: Disable ipv6 stack on all
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 sysctl_set=yes state=present

- name: Disable ipv6 stack by default
  sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 sysctl_set=yes state=present reload=yes
