---  
- name: ipv4 rpfilter enable on default
  sysctl: name=net.ipv4.conf.default.rp_filter value=1 sysctl_set=yes state=present

- name: ipv4 rpfilter enable on all
  sysctl: name=net.ipv4.conf.all.rp_filter value=1 sysctl_set=yes state=present

- name: ipv4 syncookies enable
  sysctl: name=net.ipv4.tcp_syncookies value=1 sysctl_set=yes state=present

- name: ipv4 ICMP redirects disable
  sysctl: name=net.ipv4.conf.all.accept_redirects value=0 sysctl_set=yes state=present
  
- name: ipv4 ICMP secure redirects disable
  sysctl: name=net.ipv4.conf.all.secure_redirects value=0 sysctl_set=yes state=present
  
- name: ipv4 ICMP send redirects disable
  sysctl: name=net.ipv4.conf.all.send_redirects value=0 sysctl_set=yes state=present
  
- name: ipv4 ICMP source route redirects disable
  sysctl: name=net.ipv4.conf.all.accept_source_route value=0 sysctl_set=yes state=present

- name: ipv4 log martians
  sysctl: name=net.ipv4.conf.all.log_martians value=1 sysctl_set=yes state=present reload=yes
  