---
  - name: New user
    user: name=andrew comment="Andrew Innes" shell=/bin/bash groups=sudo append=yes

  - name: Placing key
    authorized_key: user=andrew key="{{ lookup('file', './files/authorized_keys.andrew.pub') }}"
    
  - name: Remove user
    user: name=myuser state=absent remove=yes
