---
- name: Install nodejs
  apt: pkg=nodejs-legacy state=latest update_cache=yes

- name: Install npm
  apt: pkg=npm state=latest update_cache=yes
  
- name : Install forever
  shell: npm install forever -g

- name : Install gulp
  shell: npm install gulp -g
